version: "3"
services:
 nginx:
  image: nginx
  volumes:
    - ./config/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./config/dev/nginx/healthmap.conf:/etc/nginx/sites-enabled/healthmap.conf
  ports:
    - "80:80"
    - "443:443"
  networks:
    - healthmap-net
 api:
   build: .
   volumes:
    - .:/api
    - node_modules:/api/node_modules
   ports:
    - "8020:8020"
    - "9001:9001"
   environment:
    - SERVER_HOST_NAME=http://127.0.0.1
   links:
    - job-queue
    - redis
    - postgres
   networks:
    - healthmap-net
 datalistener:
   build: .
   volumes:
    - .:/datalistener
    - node_modules:/datalistener/node_modules
   ports:
    - "3030:3030"
    - "9003:9003"
   environment:
    - SERVER_HOST_NAME=http://127.0.0.1
   links:
    - job-queue
    - redis
    - postgres
   networks:
    - healthmap-net
 redis:
   image: redis
   volumes:
    - ./config/dev/redis/redis.conf:/usr/local/etc/redis/redis.conf
    - ./data/redis:/data
   ports:
    - "6379:6379"
   networks:
    - healthmap-net
   command: redis-server /usr/local/etc/redis/redis.conf
 postgres:
   image: postgres:10.9
   environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=dev
    - POSTGRES_DB=healthmap
   ports:
    - "5432:5432"
    - "5433:5433"
   networks:
    - healthmap-net
 job-queue:
   image: shippify/job-queue
   environment:
    - JOB_QUEUE_USERNAME=map
    - JOB_QUEUE_PASSWORD=dev
    - JOB_QUEUE_REDIS_HOST=job-queue-redis
   links:
    - job-queue-redis
   ports:
    - "3030:3030"
   networks:
    - healthmap-net
 job-queue-redis:
   image: redis
   volumes:
    - ./config/dev/redis/redis.conf:/usr/local/etc/redis/redis.conf
    - ./data/kue:/data
   ports:
    - "6379"
   networks:
    - healthmap-net
   command: redis-server /usr/local/etc/redis/redis.conf
volumes:
 node_modules:
networks:
 healthmap-net:
   driver: bridge